Resources:
  OFGMWebpage:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: Stage
              Value: ${self:provider.stage}
            - Key: Service
              Value: ${self:service}
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: ${self:service}
  AllowCloudfront:
    Type: AWS::S3::BucketPolicy
    DependsOn: MainOAI
    Properties: 
      Bucket: !Ref OFGMWebpage
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${OFGMWebpage}/*
            Principal: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${MainOAI}